# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='H22led',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inimese_nimi', models.CharField(max_length=200)),
                ('h22lte_arv', models.IntegerField(default=0)),
            ],
        ),
    ]
